language: c
compiler:
  - gcc
before_install:
  - pip install --user cpp-coveralls
script:
  - autoreconf -vi && ./configure --enable-gcov && make && make check
after_success:
  - coveralls --exclude tests
